{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "links": {"attachments": {"href": "data/repositories/levitsky/pyteomics/issues/21/attachments_page=1.json"}, "self": {"href": "data/repositories/levitsky/pyteomics/issues/21.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/levitsky/pyteomics/issues/21/watch"}, "comments": {"href": "data/repositories/levitsky/pyteomics/issues/21/comments_page=1.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/21/cant-get-the-mzidentml-schema-for-version"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/levitsky/pyteomics/issues/21/vote"}}, "reporter": null, "title": "Can't get the mzIdentML schema for version", "component": null, "votes": 0, "watches": null, "content": {"raw": "I'm trying to use the mzid function to open MzIdentMl 1.2 files and it says that is not possible to get the schema, and for that reason, the pyton program is unable to select the information that I need.\r\n\r\nIs it pyteomics only suitable for MzIdentMl 1.1 files?", "markup": "markdown", "html": "<p>I'm trying to use the mzid function to open MzIdentMl 1.2 files and it says that is not possible to get the schema, and for that reason, the pyton program is unable to select the information that I need.</p>\n<p>Is it pyteomics only suitable for MzIdentMl 1.1 files?</p>", "type": "rendered"}, "assignee": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2018-02-05T12:05:18.058301+00:00", "milestone": null, "updated_on": "2018-02-05T21:47:01.646628+00:00", "type": "issue", "id": 21}