{"changes": {"attachment": {"new": "example2.mzid", "old": null}}, "links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/21/changes/43101015.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/21#comment-43101015"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/21.json"}}, "type": "issue", "id": 21, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "Can't get the mzIdentML schema for version"}, "created_on": "2018-02-05T20:00:12.869977+00:00", "user": {"display_name": "Esteban", "uuid": "{dddf4552-e30d-496e-8482-d2135d035a77}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bdddf4552-e30d-496e-8482-d2135d035a77%7D"}, "html": {"href": "https://bitbucket.org/%7Bdddf4552-e30d-496e-8482-d2135d035a77%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/fae14e2182cfc76ad9d5654b177cc5a3d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsE-5.png"}}, "nickname": "stiven42", "type": "user", "account_id": "5a78b593082eb06819241284"}, "message": {"raw": "In this does not works", "markup": "markdown", "html": "<p>In this does not works</p>", "type": "rendered"}, "type": "issue_change", "id": 43101015}