{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47/comments/54493389.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/47#comment-54493389"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47.json"}}, "type": "issue", "id": 47, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "non-ascii characters in AuditCollection lead to UnicodeEncodeError"}, "content": {"raw": "Is it a problem that this hard-codes for UTF-8? What happens if other encoding schemes are used for the mzIdentML?", "markup": "markdown", "html": "<p>Is it a problem that this hard-codes for UTF-8? What happens if other encoding schemes are used for the mzIdentML?</p>", "type": "rendered"}, "created_on": "2019-10-23T07:22:57.400887+00:00", "user": {"display_name": "Lutz Fischer", "uuid": "{7796ce7b-56d0-4b48-a5ee-2191230149f0}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B7796ce7b-56d0-4b48-a5ee-2191230149f0%7D"}, "html": {"href": "https://bitbucket.org/%7B7796ce7b-56d0-4b48-a5ee-2191230149f0%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/5bc9ac295b8ba5286cb9d07d/f3ad5bf8-4343-4b38-bed9-3202f68f080d/128"}}, "nickname": "Lutz", "type": "user", "account_id": "5bc9ac295b8ba5286cb9d07d"}, "updated_on": null, "type": "issue_comment", "id": 54493389}