{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47/comments/54496413.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/47#comment-54496413"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/47.json"}}, "type": "issue", "id": 47, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "non-ascii characters in AuditCollection lead to UnicodeEncodeError"}, "content": {"raw": "I don\u2019t think so. The file encoding is handled by the underlying XML parser, which produces decoded \\(Unicode\\) strings. That is actually the problem on Python2 where `unicode` is not `str`, which breaks the `str` constructor call signature. What we are doing in the fix is encoding the Unicode produced by the parser back into bytes.", "markup": "markdown", "html": "<p>I don\u2019t think so. The file encoding is handled by the underlying XML parser, which produces decoded (Unicode) strings. That is actually the problem on Python2 where <code>unicode</code> is not <code>str</code>, which breaks the <code>str</code> constructor call signature. What we are doing in the fix is encoding the Unicode produced by the parser back into bytes.</p>", "type": "rendered"}, "created_on": "2019-10-23T10:24:52.867174+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 54496413}