{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/34/comments/48909869.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/34#comment-48909869"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/34.json"}}, "type": "issue", "id": 34, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "parser fails on numbers in modX sequence"}, "content": {"raw": "created the [PR](#!/levitsky/pyteomics/pull-requests/27/add-symbol-and-number-support-for)", "markup": "markdown", "html": "<p>created the <a data-is-external-link=\"true\" href=\"#!/levitsky/pyteomics/pull-requests/27/add-symbol-and-number-support-for\" rel=\"nofollow\">PR</a></p>", "type": "rendered"}, "created_on": "2018-11-13T14:47:14.054794+00:00", "user": {"display_name": "Lars Kolbowski", "uuid": "{fc1df402-e755-41a0-b5a6-d80421a2af72}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bfc1df402-e755-41a0-b5a6-d80421a2af72%7D"}, "html": {"href": "https://bitbucket.org/%7Bfc1df402-e755-41a0-b5a6-d80421a2af72%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/5bc99e3bd64558662e6d627e/dab57bdc-7f90-48ff-9610-606fbf956a58/128"}}, "nickname": "Lars Kolbowski", "type": "user", "account_id": "5bc99e3bd64558662e6d627e"}, "updated_on": null, "type": "issue_comment", "id": 48909869}