{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5/comments/6039932.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/5#comment-6039932"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/5.json"}}, "type": "issue", "id": 5, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "crash of AMDx64 installer"}, "content": {"raw": "I tried the installer on another Win7 x64 machine, with an older Python 2.7.2, and it also worked.\n\nThe output I managed to get from the debugger doesn't help me that much: http://pastebin.com/AUQtfjYF\n\nTo be on the safe side: can you verify that your Python folder is writeable? Seems to be unrelated, but this was mentioned as a possible cause of problems with distutils-built installers on Windows in some of the search results I got.", "markup": "markdown", "html": "<p>I tried the installer on another Win7 x64 machine, with an older Python 2.7.2, and it also worked.</p>\n<p>The output I managed to get from the debugger doesn't help me that much: <a href=\"http://pastebin.com/AUQtfjYF\" rel=\"nofollow\" class=\"ap-connect-link\">http://pastebin.com/AUQtfjYF</a></p>\n<p>To be on the safe side: can you verify that your Python folder is writeable? Seems to be unrelated, but this was mentioned as a possible cause of problems with distutils-built installers on Windows in some of the search results I got.</p>", "type": "rendered"}, "created_on": "2013-09-12T20:06:48.572030+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": "2013-09-12T21:20:13.285470+00:00", "type": "issue_comment", "id": 6039932}