{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/37/comments/51813044.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/37#comment-51813044"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/37.json"}}, "type": "issue", "id": 37, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "Add numpress support in mzML"}, "content": {"raw": "So it looks like the problem has to do with the fused function dispatch\nitself. I was able to reproduce it finally, and narrow down the problem.\nI've opened the issue with Cython:\nhttps://github.com/cython/cython/issues/2932", "markup": "markdown", "html": "<p>So it looks like the problem has to do with the fused function dispatch\nitself. I was able to reproduce it finally, and narrow down the problem.\nI've opened the issue with Cython:\n<a href=\"https://github.com/cython/cython/issues/2932\" rel=\"nofollow\" class=\"ap-connect-link\">https://github.com/cython/cython/issues/2932</a></p>", "type": "rendered"}, "created_on": "2019-04-25T22:30:11.942294+00:00", "user": {"display_name": "Joshua Klein", "uuid": "{919f0add-304d-4b9a-8889-d2622a3dbc96}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B919f0add-304d-4b9a-8889-d2622a3dbc96%7D"}, "html": {"href": "https://bitbucket.org/%7B919f0add-304d-4b9a-8889-d2622a3dbc96%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/7d0e70bc74f783efa621a2bdd228ca22d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJK-3.png"}}, "nickname": "mobiusklein", "type": "user", "account_id": "557058:ff82222f-afe5-4135-a1b7-8de99a00f669"}, "updated_on": null, "type": "issue_comment", "id": 51813044}