{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/25/comments/45342628.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/25#comment-45342628"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/25.json"}}, "type": "issue", "id": 25, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "pyteomics 3.4 incompatible with current versions of pepxmltk and cythonize"}, "content": {"raw": "Thanks for reporting. I'm not used to conda and couldn't make your first command work right off the bat, but I see that if I `conda install pyteomics` and then `pip install pyteomics.pepxmltk`, it breaks pyteomics imports.\n\nThis happens because `pyteomics` is installed as an egg: `some_env/lib/python2.7/site-packages/pyteomics-3.4-py2.7.egg`, and `pyteomics.pepxmltk` installs into `some_env/lib/python2.7/site-packages/pyteomics`. Apparently the import mechanism then ignores the egg when looking for modules.", "markup": "markdown", "html": "<p>Thanks for reporting. I'm not used to conda and couldn't make your first command work right off the bat, but I see that if I <code>conda install pyteomics</code> and then <code>pip install pyteomics.pepxmltk</code>, it breaks pyteomics imports.</p>\n<p>This happens because <code>pyteomics</code> is installed as an egg: <code>some_env/lib/python2.7/site-packages/pyteomics-3.4-py2.7.egg</code>, and <code>pyteomics.pepxmltk</code> installs into <code>some_env/lib/python2.7/site-packages/pyteomics</code>. Apparently the import mechanism then ignores the egg when looking for modules.</p>", "type": "rendered"}, "created_on": "2018-05-09T20:48:31.015794+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 45342628}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/25/comments/45601706.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/25#comment-45601706"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/25.json"}}, "type": "issue", "id": 25, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "pyteomics 3.4 incompatible with current versions of pepxmltk and cythonize"}, "content": {"raw": "Thanks for looking into it. I've reported the issues on the bioconda-recipes github (including what you found about the `egg` vs `pyteomics` folder), since the issue only appear to be with installation through conda.", "markup": "markdown", "html": "<p>Thanks for looking into it. I've reported the issues on the bioconda-recipes github (including what you found about the <code>egg</code> vs <code>pyteomics</code> folder), since the issue only appear to be with installation through conda.</p>", "type": "rendered"}, "created_on": "2018-05-18T21:30:40.140137+00:00", "user": {"display_name": "mglubber", "uuid": "{559bde61-bb9f-484b-b183-1b21bb8b4bb0}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B559bde61-bb9f-484b-b183-1b21bb8b4bb0%7D"}, "html": {"href": "https://bitbucket.org/%7B559bde61-bb9f-484b-b183-1b21bb8b4bb0%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/f188803c05340901eba88626b4b308d9d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsM-0.png"}}, "nickname": "mglubber", "type": "user", "account_id": "5af0862cfd53c72c28995f3f"}, "updated_on": null, "type": "issue_comment", "id": 45601706}, {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/25/comments/46016562.json"}, "html": {"href": "#!/levitsky/pyteomics/issues/25#comment-46016562"}}, "issue": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics/issues/25.json"}}, "type": "issue", "id": 25, "repository": {"links": {"self": {"href": "data/repositories/levitsky/pyteomics.json"}, "html": {"href": "#!/levitsky/pyteomics"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3f6302de-10da-4d3c-b258-0bb6a2368972}ts=74456"}}, "type": "repository", "name": "pyteomics", "full_name": "levitsky/pyteomics", "uuid": "{3f6302de-10da-4d3c-b258-0bb6a2368972}"}, "title": "pyteomics 3.4 incompatible with current versions of pepxmltk and cythonize"}, "content": {"raw": "Closing as this has been [fixed on the bioconda side](https://github.com/bioconda/bioconda-recipes/issues/8971).", "markup": "markdown", "html": "<p>Closing as this has been <a data-is-external-link=\"true\" href=\"https://github.com/bioconda/bioconda-recipes/issues/8971\" rel=\"nofollow\">fixed on the bioconda side</a>.</p>", "type": "rendered"}, "created_on": "2018-06-07T10:32:13.515882+00:00", "user": {"display_name": "Lev Levitsky", "uuid": "{eb44325f-4ee0-4e0b-a27c-f2ea23122a56}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D"}, "html": {"href": "https://bitbucket.org/%7Beb44325f-4ee0-4e0b-a27c-f2ea23122a56%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a2593c44c42429c503d2e5e9e307e241d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsLL-6.png"}}, "nickname": "levitsky", "type": "user", "account_id": "557058:986c547b-c50a-40b3-948a-29b4a93b7b30"}, "updated_on": null, "type": "issue_comment", "id": 46016562}], "page": 1, "size": 3}